use_frameworks!

platform :ios, '8.0'

target 'EYQRCodeTools_Example' do
  pod 'EYQRCodeTools', :path => '../'

  target 'EYQRCodeTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
